# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login_Register', '0001_initial'),
        ('Travel_Dashboard', '0002_trip_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAndTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_going', to='Travel_Dashboard.Trip')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_going', to='Login_Register.User')),
            ],
        ),
    ]
