# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_Dashboard', '0003_userandtrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='startDate',
            field=models.DateField(),
        ),
    ]
